### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by acodingsquirrel** [acodingsquirrel/diabolo-jeykll#2]
https://github.com/acodingsquirrel/diabolo-jeykll/blob/2aa8717df893222679617cd9bad1394223724bf0/_layouts/default.html#L21

**Comment by acodingsquirrel** [comment]
Frage 1: Zu /pages/shows.md kann ich kein Issue erstellen, was zu einer Zeile gehört. Warum nicht?

Frage 2: 
IST:
Wenn ich in Zeile 6 von /pages/shows.md einfach nur den Youtube-Link austausche mit
https://www.youtube.com/watch?v=_TgKxRnP-qE&t=9s
funktioniert es nicht. 
Auf YouTube lässt sich die Datei mit dem Link abspielen. Auch der vorherige Link: 
https://www.youtube.com/embed/1-2e9Da8C3E
hat funktioniert.
SOLL:
Auf der Seite Shows ist auch das Video "Diabolo Salad" aus YouTube eingebunden.

**Comment by caspii** [comment]
Du kannst den Link nicht einfach austauschen, da es ein spezial Link ist. Diesen musst Du dir erst auf Youtube besorgen: Share > Embed

![image](https://user-images.githubusercontent.com/3215971/46920992-3f8e6080-cff6-11e8-8a57-6e7f5d8567c2.png)
