### ISSUE TITLE
Alles ist rot

### ISSUE THREAD

**Issue by acodingsquirrel** [acodingsquirrel/diabolo-jeykll#3]
https://github.com/acodingsquirrel/diabolo-jeykll/blob/e9d393fa050764f92672c1d8ae1f82cacc9af0df/_layouts/default.html#L41

Super, der Text ist da. 

IST:
Jetzt ist die ganze Seite rot.

SOLL:
Die Überschriftszeile ist rot.
Der Text ist normal weiß.

**Comment by caspii** [comment]
Alles ist rot, weil 2 `<div>` nicht geschlossen wurden. Man schliesst sie mit`</div>`

Allerdings sieht es nach dem Fix immer noch nicht korrekt aus 🤔
