### ISSUE TITLE
Seite als "Github Pages" hosten

### ISSUE THREAD

**Issue by caspii** [acodingsquirrel/diabolo-jeykll#6]

**Comment by acodingsquirrel** [comment]
Gefunden habe ich Wege ein neues Repo anzulegen und darauf die Seite zu hosten. Das gefällt mir nicht, weil ich ja schon ein Repo mit einer funktionierenden Seite habe.

Alternativen mit orphan-branches habe ich nicht verstanden. 
Smooth wäre: ich lasse mein jetztiges repo zum github-repo werden. Ein Topic für die nächste dev101 Session?

**Comment by acodingsquirrel** [comment]
Die Bilder funktionieren jetzt nicht...

Dabei habe ich keine Anleitung für relative Links bei Bildern gefunden. Meine Versuche es ähnlich wie bei den Seitenlinks zu lösen haben nicht funktioniert. Dazu der letzte Commit "try different diabolos pictures relative Links" bei pages. 

Für mich genauso wenig nachvollziehbar ist, das komischerweise das Bild aus der Indexseite funktioniert. Die Bilder auf den Seiten "Kinds of Diabolos" und "Tricks" nicht.

**Comment by caspii** [comment]
Die Syntax war nicht korrekt. Ich hab's korrigiert. Schau dir diesen Commit genau an, um es zu verstehen: https://github.com/acodingsquirrel/diabolo-jeykll/commit/01149f3f94979fd278f9f1d41a29a924cae03607
