### ISSUE TITLE
Use local CSS for Bootstrap instead of Bootswatch version

### ISSUE THREAD

**Issue by acodingsquirrel** [acodingsquirrel/diabolo-jeykll#7]
Download this file, check into repo, and link in `default.html`

**Comment by acodingsquirrel** [comment]
Wo kann ich die Datei zum Download herbekommen? Ich finde nicht die Datei, die ich brauche bzw. eine Anleitung, die mir hilft

**Comment by caspii** [comment]
Du klickst hier auf den gewünschten Download Button: https://bootswatch.com/

Kann sein, dass die CSS Datei im Browser öffnet, ohne sie zu speichern. Dann drückst Du STRG+S um die Datein aus dem Browser heraus zu speichern

**Comment by caspii** [comment]
Oder noch cooler, du machst im richtigen Verzeichnis auf der Kommandozeile `wget https://bootswatch.com/4/lumen/bootstrap.min.css`

**Comment by acodingsquirrel** [comment]
Es hat funktioniert. Ich habe die Änderung schon eingecheckt.
