### ISSUE TITLE
Eine neue Domäne registrieren und auf GitHub zeigen lassen

### ISSUE THREAD

**Issue by caspii** [acodingsquirrel/diabolo-jeykll#8]
Schritte
1. Domäne ausdenken
2. Domäne registrieren bei einem Domain Registrar : ZB: bei dnsimple.com, oder df.eu, oder ...
3. DNS so einrichten, dass es auf GitHub zeigt: https://help.github.com/articles/using-a-custom-domain-with-github-pages/

**Comment by acodingsquirrel** [comment]
Haben wir diesen Freitag gemacht!
