### ISSUE TITLE
Navbar broken

### ISSUE THREAD

**Issue by acodingsquirrel** [acodingsquirrel/diabolo-jeykll#9]
https://github.com/acodingsquirrel/diabolo-jeykll/blob/396b7a2736dea115a14f236e68717e8319900cae/_layouts/default.html#L27

Ich habe relative Pfade angegeben. 
Jetzt funktioniert die Navigation auf der Seite auch im Internet.
 
In Layouts Zeile 27 hat das einfügen von relativen Pfaden auch dazu geführt, das die Navbar jetzt doppelt so hoch ist und die einzelnen Menüpunkte ungleichmäßig angeordnet sind.
Wie kann ich das reparieren?

Ich vermute das in dieser Zeile ein Fehler liegt. Diese Vermutung habe ich, weil ich lokal die Zeile auskommentiert habe und die Navbar wieder schön aussah.

**Comment by caspii** [comment]
NICE! ☀️

Deine Vermutung ist richtig. Du hast den `a` Tag kaputt gemacht (Hint: das hat nichts mit dem relative_path zu tun). Schau dir mal das generierte HTML an, dann siehst du hoffentlich den Fehler

Außerdem fehlt in dem `a` Tag ein verlinkter Text!
